# Nightfox Alacritty Colors
# Style: nightfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox_alacritty.yml
font:
  size: 11
  normal:
    family: Inconsolata # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: Inconsolata # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: Inconsolata # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Italic

schemes:
  nightfox: &nightfox
    primary:
      background: '0x192330'
      foreground: '0xcdcecf'
    # Normal colors
    normal:
      black:   '0x393b44'
      red:     '0xc94f6d'
      green:   '0x81b29a'
      yellow:  '0xdbc074'
      blue:    '0x719cd6'
      magenta: '0x9d79d6'
      cyan:    '0x63cdcf'
      white:   '0xdfdfe0'
    # Bright colors
    bright:
      black:   '0x575860'
      red:     '0xd16983'
      green:   '0x8ebaa4'
      yellow:  '0xe0c989'
      blue:    '0x86abdc'
      magenta: '0xbaa1e2'
      cyan:    '0x7ad4d6'
      white:   '0xe4e4e5'
    indexed_colors:
      - { index: 16, color: '0xf4a261' }
      - { index: 17, color: '0xd67ad2' }

  dayfox: &dayfox
    # Default colors
    primary:
      background: '0xeaeaea'
      foreground: '0x1d344f'
    # Normal colors
    normal:
      black:   '0x1d344f'
      red:     '0xb95d76'
      green:   '0x618774'
      yellow:  '0xba793e'
      blue:    '0x4d688e'
      magenta: '0x8e6f98'
      cyan:    '0x6ca7bd'
      white:   '0xcdd1d5'
    # Bright colors
    bright:
      black:   '0x24476f'
      red:     '0xc76882'
      green:   '0x629f81'
      yellow:  '0xca884a'
      blue:    '0x4e75aa'
      magenta: '0x9f75ac'
      cyan:    '0x74b2c9'
      white:   '0xcfd6dd'
    indexed_colors:
      - { index: 16, color: '0xe3786c' }
      - { index: 17, color: '0xd685af' }

  dawnfox: &dawnfox
    # Default colors
    primary:
      background: '0xfaf4ed'
      foreground: '0x575279'
    # Normal colors
    normal:
      black:   '0x575279'
      red:     '0xb4637a'
      green:   '0x618774'
      yellow:  '0xea9d34'
      blue:    '0x286983'
      magenta: '0x907aa9'
      cyan:    '0x56949f'
      white:   '0xe5e9f0'
    # Bright colors
    bright:
      black:   '0x5f5695'
      red:     '0xc26d85'
      green:   '0x629f81'
      yellow:  '0xeea846'
      blue:    '0x2d81a3'
      magenta: '0x9a80b9'
      cyan:    '0x5ca7b4'
      white:   '0xe6ebf3'
    indexed_colors:
      - { index: 16, color: '0xd7827e' }
      - { index: 17, color: '0xd685af' }

colors: *dayfox

cursor:
  style:
    shape: Block
    blinking: Never

draw_bold_text_with_bright_colors: true
