# Nightfox Alacritty Colors
# Style: nightfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox_alacritty.yml
font:
  size: 11
  normal:
    family: Inconsolata # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: Inconsolata # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: Inconsolata # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Italic

colors:
  # Default colors
  primary:
    background: '0x192330'
    foreground: '0xcdcecf'
  # Normal colors
  normal:
    black:   '0x393b44'
    red:     '0xc94f6d'
    green:   '0x81b29a'
    yellow:  '0xdbc074'
    blue:    '0x719cd6'
    magenta: '0x9d79d6'
    cyan:    '0x63cdcf'
    white:   '0xdfdfe0'
  # Bright colors
  bright:
    black:   '0x575860'
    red:     '0xd16983'
    green:   '0x8ebaa4'
    yellow:  '0xe0c989'
    blue:    '0x86abdc'
    magenta: '0xbaa1e2'
    cyan:    '0x7ad4d6'
    white:   '0xe4e4e5'
  indexed_colors:
    - { index: 16, color: '0xf4a261' }
    - { index: 17, color: '0xd67ad2' }

cursor:
  style:
    shape: Block
    blinking: Never

draw_bold_text_with_bright_colors: true
